server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/jd_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&connectTimeout=30000&socketTimeout=15000&autoReconnectForPools=true&allowMultiQueries=true&failOverReadOnly=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  aop:
    proxy-target-class: true
    auto: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /*.xml
  type-aliases-package: com.demo.ql.domain