server:
  port: 8081 # 服务端口

spring:
  profiles:
    active: ql # 当前使用的配置文件
  application:
    name: web-demo # 项目名

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # Mybatis XML路径